api/urls.py
from django.urls import path
from . import views

app_name = 'api'
urlpatterns = [
    #Home
    path('', views.api, name='api'),
    path('get_topic/(<int:topic_id>)/', views.get_topic, name='topic'),
    path('get_topics/', views.get_topics, name='get_topics'),
    # path('add_topic/', views.add_topic, name='add_topic'),        
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve


urlpatterns = [  
    path('admin/', admin.site.urls),
    path('', include('blogapp.urls')),
    path('users/', include('users.urls')),
    path('api/', include('api.urls')), 
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/views.py
from django.shortcuts import render
from rest_framework.response import Response
from rest_framework.decorators import api_view
from .serializers import TopicSerializer

from blogapp.models import Topic

def api(request):
  return render(request, 'api/api.html')

@api_view(['GET'])
def get_topics(request):
  topics = Topic.objects.filter(confirmed=True)
  serializer = TopicSerializer(topics, many=True)
  return Response(serializer.data)

@api_view(['GET'])
def get_topic(request, topic_id):
  topic = Topic.objects.get(id= topic_id)
  serializer = TopicSerializer(topic, many=False)
  return Response(serializer.data)

# @api_view(['POST'])
# def add_topic(request):
#   serializer = TopicSerializer(data=request.data)
#   if serializer.is_valid():
#     serializer.save()
#   return Response(serializer.data)

api/templates/api/api.html
{% extends 'blogapp/base_container.html' %}
{% load static %}
{% block content %}

<header class="p-3 border-bottom mb-5">  
    <i class="fa-solid fa-circle-nodes fa-2xl "></i>
    <span class="fs-4 ms-3 fw-bold">Rest API</span>
</header>


  <h4>Dostęp do danych listy zatwierdzonych tematów:</h4>
  <p class="py-3">{% url 'api:get_topics' %}?format=json</p>
  <h4>Dostęp do danych pojedynczego tematu:</h4>
  <p class="py-3">{% url 'api:api' %}get_topic/(<i>ID_TEMATU</i>)/?format=json</p>
  

{% endblock content %}