api/urls.py
from django.urls import path
from . import views

app_name = 'api'
urlpatterns = [
    #Home
    path('', views.api, name='api'),
    path('get_topic/(<int:topic_id>)/', views.get_topic, name='topic'),
    path('get_topics/', views.get_topics, name='get_topics'),
    # path('add_topic/', views.add_topic, name='add_topic'),        
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve


urlpatterns = [  
    path('admin/', admin.site.urls),
    path('', include('blogapp.urls')),
    path('users/', include('users.urls')),
    path('api/', include('api.urls')), 
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogapp/urls.py
from django.urls import path

from . import views

app_name = 'blogapp'
urlpatterns = [
    #Home
    path('', views.home, name='home'),
    path('<int:page_nr>/', views.index, name='index'),

    #Sites
    path('about/', views.about, name='about'),
    path('gallery/', views.gallery, name='gallery'),
    path('terms/', views.terms, name='terms'),

    #Topic
    path('topic/(<int:topic_id>)/', views.topic, name='topic'),
    path('new_topic/', views.new_topic, name='new_topic'),
    path('edit_topic/(<int:topic_id>)/', views.edit_topic, name='edit_topic'),
    path('delete_topic/(<int:topic_id>)/', views.delete_topic, name='delete_topic'),

    #topics lists
    path('pending_topics/', views.pending_topics, name='pending_topics'),
    path('confirm_topic/(<int:topic_id>)', views.confirm_topic, name='confirm_topic'),
    path('my_topics/', views.my_topics, name='my_topics'),
     
    #Images
    path('add_image/(<int:topic_id>)/', views.add_image, name='add_image'),
    path('delete_image/(<int:topic_id>-<int:image_id>)/', views.delete_image, name='delete_image'),

    #search
    path('search_topic/', views.search_topic, name='search_topic') ,
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name = 'register'),
    path('logged_out/', views.logged_out, name = 'logged_out'),
    path('user_account/', views.user_account, name='user_account'),
    path('view_account/(<str:username>)/', views.view_account, name='view_account'),
]
    

blogapp/models.py
from django.db import models
from django.contrib.auth.models import User
# import PIL.Image

def images_path(instance, filename):
    return "{}/{}".format(instance.topic.title, filename)

def topic_images_path(self, filename):
    return "{}/{}".format(self.title, filename)

class Topic(models.Model):
    title = models.CharField(max_length=30)
    description = models.CharField(max_length=600)
    text = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True)
    header_image = models.ImageField(blank=True, upload_to=topic_images_path)
    header_image_description = models.CharField(max_length=200, blank=True)
    confirmed = models.BooleanField(default=False)

    @property
    def short_description(self):
        if len(self.description)> (lenght:=270):
            return self.description[:lenght]+'...'
        else:
            return self.description
    
    def __str__(self):
        return self.title.capitalize()

    # def save(self, *args, **kwargs):
    #     super().save(*args, **kwargs)
    #     # if self.header_image:            
    #     #     img = PIL.Image.open(self.header_image)

    #     #     output_size = (1600, 768)
    #     #     new_img= img.resize(output_size)
    #     #     new_img.save(self.header_image.name+'.'+img.format)

    #         # fh = storage.open(self.header_image.name, "w")
    #         # format = img.format
    #         # new_img.save(fh, format)
    #         # fh.close()
    #         # new_img.save(self.header_image.path)

    #         # fh = storage.open(self.header_image.name, "w")
    #         # format = img.format
    #         # new_img.save(fh, format)
    #         # fh.close()

class Comment(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.CharField(max_length=600)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    owner = models.ForeignKey(User, on_delete=models.PROTECT)

class Image(models.Model):
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=100)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=images_path)
    show_in_gallery = models.BooleanField(default=True)

blogapp/forms.py
from django import forms
from .models import Topic, Comment, Image

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        labels = {'text': ''}
        widgets =  {'text' : forms.Textarea(attrs={'rows': 10, 'cols':60},)}

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic        
        fields = ['title', 'description', 'text', 'header_image', 'header_image_description']
        widgets =  {
            'text' : forms.Textarea(attrs={
                'placeholder': 'Aby dodać nagłówek, umieść go między tagami "<h4></h4>". \nTreść umieść pomiędzy tagami "<p></p>"'
                    '\n\nPrzykład:\n\n<h4>Twój nagłówek</h4>\n\n<p>Twoja treść</p>'}),
                'rows': 20,
            'description': forms.Textarea(attrs={'rows':3}),            
            }


class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['name', 'description', 'image']      
     

blogapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, permission_required
from django.conf import settings
from users.decorators import allowed_users

import os, shutil

from .models import Topic, Image
from .forms import CommentForm, TopicForm, ImageForm

def home(request):
    return redirect ('/0/')

def index(request, page_nr):
    all_topics = Topic.objects.filter(confirmed=True).order_by('-date_created')
    
    last_topic = all_topics[0] 
    topics = all_topics[1:]

    

    numbers_of_topic_for_single_page = 6
    tpp = numbers_of_topic_for_single_page
     
    if len(topics) - (page_nr * tpp + tpp) >= 0:
        visible_topics = topics[page_nr*tpp : page_nr*tpp+tpp]
    elif len(topics) - (page_nr * tpp + tpp) < tpp > 0:
        visible_topics = topics[page_nr*tpp : ]

    class Page():
        def __init__(self):
            self.nr = page_nr
            self.last_nr = int(len(topics) / (tpp+1))
            self.next_nr = self.nr + 1
            if self.nr >0:
                self.prev_nr = self.nr - 1
            else:
                self.prev_nr = 0    
    
    page = Page()

    context = {'topics': visible_topics, 'last_topic':last_topic, 'page': page,}
    return render(request, 'blogapp/index.html', context)

def about(request):
    return render(request, 'blogapp/about.html')

def terms(request):
    return render(request, 'blogapp/terms.html')

def gallery(request):
    all_images = Image.objects.all()    
                
    context={"images":all_images}
    return render(request, 'blogapp/gallery.html',context)

def search_topic(request):
    all_topics = Topic.objects.filter(confirmed=True).order_by('-date_created')
    topics = []
    if request.method == 'POST':
        searched = request.POST['searched']
        for topic in all_topics:
            if searched.lower() in topic.title.lower():
                topics.append(topic)
    context ={'topics': topics, 'searched':searched}
    return render(request, 'blogapp/search_topic.html', context)

def topic(request, topic_id, image_id=None):
    topic =    get_object_or_404(Topic, id=topic_id)
    comments = topic.comment_set.order_by('-date_created')
    images = topic.image_set.all()

    #Add new comment form
    if request.method != 'POST':
        form = CommentForm()
    else:
        if image_id:
            redirect ('blogapp:delete_image', topic_id, image_id)
        form = CommentForm(data=request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.topic = topic
            new_comment.owner = request.user
            new_comment.save()        
   
    context ={'topic': topic, 'comments': comments, 'form': form,'images':images,}
    return render(request, 'blogapp/topic.html', context)

@login_required
def my_topics(request):    
    # topics = Topic.objects.filter(owner=request.user).order_by('-date_created')
    topics = request.user.topic_set.order_by('-date_created')
    
    context = {'topics': topics,}
    return render(request, 'blogapp/my_topics.html', context)

@login_required
@permission_required('is_staff', raise_exception=True)
def pending_topics(request):
    topics = Topic.objects.filter(confirmed=False).order_by('-date_created')
    
    context = {'topics': topics,}
    return render(request, 'blogapp/pending_topics.html', context)

@login_required
@permission_required('is_staff', raise_exception=True)
def confirm_topic(request, topic_id):
    topic = get_object_or_404(Topic, id=topic_id)
    if request.method =='POST':        
        topic.confirmed = True
        topic.save()
    return redirect('blogapp:pending_topics')

@login_required
@permission_required('blogapp.add_topic', raise_exception=True)
def new_topic(request):
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(request.POST, request.FILES)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner= request.user
            new_topic.save()
            # create media dir
            if not new_topic.title in os.listdir(settings.MEDIA_ROOT):
                os.mkdir(os.path.join(settings.MEDIA_ROOT, new_topic.title))
            return redirect('blogapp:home')

    context = {'form': form}
    return render(request, 'blogapp/new_topic.html', context)


@login_required
@permission_required('blogapp.change_topic', raise_exception=True)
def edit_topic(request, topic_id):
    topic = get_object_or_404(Topic, id=topic_id)

    if request.method != 'POST':
        form= TopicForm(instance=topic)
    else:
        form = TopicForm(request.POST, request.FILES, instance=topic)
        if form.is_valid:
            form.save()
            return redirect('blogapp:topic', topic.id)

    context = {'topic':topic, 'form':form}

    return render(request, 'blogapp/edit_topic.html', context)


@login_required
@permission_required('blogapp.delete_topic', raise_exception=True)
def delete_topic(request, topic_id):
    topic = get_object_or_404(Topic, id=topic_id)
    if request.method =='POST':
        topic.delete()
        #del dir
        if os.path.exists(os.path.join(settings.MEDIA_ROOT, topic.title)):             
            shutil.rmtree(os.path.join(settings.MEDIA_ROOT, topic.title))
        return redirect('blogapp:home')

    context = {'topic':topic}
    
    return render(request, 'blogapp/delete_topic.html', context)


@login_required
def add_image(request, topic_id):
    topic = get_object_or_404(Topic, id=topic_id)

    if request.method != 'POST':
        form= ImageForm()
    else:
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid:             
            checkbox_value = request.POST.get('show_in_gallery')
            new_image = form.save(commit=False)
            if not checkbox_value:
                new_image.show_in_gallery = False
            new_image.topic= topic
            new_image.save()
            return redirect('blogapp:topic', topic_id=topic.id)
    context = {'topic':topic, 'form':form}
    return render(request, 'blogapp/add_image.html', context)


def delete_image(request, topic_id, image_id):
    image = get_object_or_404(Image, id=image_id)
    image.delete()
    return redirect('blogapp:topic', topic_id)

blogapp/templates/blogapp/add_image.html
{% extends 'blogapp/base_container.html' %}
{% block content %}

<header class="p-3 border-bottom mb-5">
  <i class="fa-solid fa-image fa-2xl"></i>
  <span class="fs-4 ms-3 fw-bold">Dodaj zdjęcie dla tematu "{{topic.title}}"</span>
</header>

  <div class="row justify-content-center">
    <div class="col-md-6">
      <form class='my-3' action="{% url 'blogapp:add_image' topic.id %}" method = 'post' enctype="multipart/form-data">
          {% csrf_token %}
          <div id="form_text_inputs">
            <div class="mb-3">
              <label for="name" class="form-label">Tytuł:</label>
              {{form.name}}
              <div class="form-text">Krótka nazwa grafiki.</div>
            </div>
            <div class="mb-3">
              <label for="description" class="form-label">Opis grafiki:</label>
              {{form.description}}
              <div class="form-text">Krótki opis zdjęcia do 100 znaków.</div>
            </div>    
            <div class="mb-5">
                <label for="image" class="form-label ">Wybierz zdjęcie:</label>
                {{form.image}}
              </div>
          </div>
            <div class="form-check mb-5">
              <input class="form-check-input" type="checkbox" value="True" name="show_in_gallery" checked="true">
              <label class="form-check-label" for="show_in_gallery">Pokaż w galerii</label>
            </div>
          <button type="submit" class="btn btn-primary">Zapisz</button>
      </form>
    </div>
  </div>

    <script>
        var form_fields = form_text_inputs.getElementsByTagName('input')
        for (var field in form_fields){	
          form_fields[field].className += ' form-control'
        }
    </script>

{% endblock content %}

blogapp/templates/blogapp/base_container.html
{% extends 'blogapp/base_nocontainer.html' %}

{% block base %}
  <div class="container my-3">
    {% block content %}{% endblock content %}
  </div>
{% endblock base %}

blogapp/templates/blogapp/base_nocontainer.html
{% load static %}

<!doctype html>
<html lang="pl">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Geostrat.pl</title>
    <!-- BOOTSTRAP 5 -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/web.css' %}">
    <!-- FONTAWESOME -->
    <script src="{% static 'fontawesomefree/js/all.min.js' %}"></script>
    <!-- GOOGLE FONTS -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Crimson+Text:ital,wght@0,400;0,700;1,400;1,700&family=Rubik+Dirt&display=swap" rel="stylesheet">

  </head>

  <body>
    <!-- NAVBAR -->
    <nav class="navbar navbar-dark bg-dark navbar-expand-lg bg-gradient user-select-none fs-4">      
      <a class="navbar-brand text-uppercase ms-3 mt-2" href="{% url 'blogapp:home' %}">
        <h1 class="ff-rd text-light">Geostrat</h1>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mainmenu" aria-controls="mainmenu" aria-expanded="false" aria-label="Toggle navigation"> 
        <span class="navbar-toggler-icon text-light" ></span>
      </button>

      <div class="collapse navbar-collapse" id="mainmenu">
        <ul class="navbar-nav me-auto">
          <li><hr class="dropdown-divider"></li>
          <li class="nav-item">
            <a class ="nav-link link-primary" href="{% url 'blogapp:gallery' %}">GALERIA</a>
          </li>
          <li class="nav-item">
            <a class ="nav-link" href="{% url 'blogapp:about' %}">O STRONIE</a>
          </li>
          <li class="nav-item">
            <a class ="nav-link" href="{% url 'blogapp:terms' %}">REGULAMIN</a>
          </li>
        </ul>

        <form class="d-flex me-5 ff-rd" action="{% url 'blogapp:search_topic' %}" method = 'post'>
          {% csrf_token %}
          <input class="form-control me-2" type="search" name="searched" placeholder="znajdź temat..." aria-label="Search">
          <button class="btn btn-outline-primary" type="submit">Szukaj</button>
        </form>

        <ul class="navbar-nav me-3">
          {% if user.is_authenticated %}
          <li class="nav-item mt-2 me-2">
            <a class="" href="{% url 'users:user_account' %}"> {{user.bloguser.name}}</a>
          </li>
          <li>
            {% if request.user.bloguser.profile_picture %}
            <img class="nav-item user-select-none rounded-circle" style="max-height:50px;" src='{{request.user.bloguser.profile_picture.url}}' alt="profile_picture">          
            {% else %}
            <img class="nav-item user-select-none rounded-circle" style="max-height:50px;" src="{% static 'images/_defaults/default_user.png' %}" alt="default_picture"> 
            {% endif %}
          </li>
          <li class="nav-item">
            <a class="nav-link " href="{% url 'users:logged_out' %}">WYLOGUJ SIĘ</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class ="nav-link link-light" href="{% url 'users:login' %}">ZALOGUJ SIĘ</a>
          </li>
          <li class="nav-item">
            <a class ="nav-link link-light" href="{% url 'users:register' %}">ZAREJESTRUJ SIĘ</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <!-- USER LOGGED PANEL-->
    {% if request.user.is_authenticated %}
      {% if perms.blogapp.add_topic %}
      <div class="container nav-scroller mb-2 link-dark fw-bold">
        <nav class="nav d-flex justify-content-evenly link-dark">
          <a class="p-2 link-secondary" href="{% url 'blogapp:pending_topics' %}">Oczekujące tematy</a>          
          <a class="p-2 link-secondary" href="{% url 'blogapp:my_topics' %}">Moje tematy</a>        
          <a class="p-2 link-secondary" href="{% url 'blogapp:new_topic' %}">Dodaj temat</a>                
          <a class="p-2 link-secondary" href="{% url 'users:user_account' %}">Konto Użytkownika</a>   
        </nav>
      </div>
      {% endif %} 
    {% endif %}    
      
      <!-- MAIN -->
      {% block base %}
      {% endblock base %}
      
      <!-- FOOTER -->
      <footer class="mt-auto bg-dark bg-gradient p-2">  
        <div class="container">   
          <div class="row text-light">          
            <div class="col-lg-4 col-12 d-flex flex-column align-items-center py-3">
              <h5 class="text-center fs-4 ff-rd">KONTAKT</h5>
                <ul class="nav mt-4">
                  <li class="nav-item"><a class="nav-link" href="https://rogalskitportfolio.herokuapp.com/"><i class="fa-solid fa-globe fa-3x"></i></a></i></li>
                  <li class="nav-item"><a class="nav-link" href="https://github.com/Tomasz-Rogalski?tab=repositories"><i class="fa-brands fa-github fa-3x"></a></i></li>
                  <li class="nav-item"><a class="nav-link" href="https://www.linkedin.com/in/tomasz-rogalski-2a3b97138/"><i class="fa-brands fa-linkedin fa-3x"></a></i></li>
                  <li class="nav-item"><a class="nav-link" href="https://www.facebook.com/torogalski/"><i class="fa-brands fa-facebook fa-3x"></a></i></li>
                </ul>
            </div>
            <div class="col-lg-4 col-6 d-flex flex-column align-items-center py-3">
              <h5 class="text-center fs-4 ff-rd">NAWIGACJA</h5>
              <ul class="nav flex-column mt-2">
                <li class="nav-item">
                  <a class ="nav-link" href="{% url 'blogapp:home' %}">Strona główna</a>
                </li>
                <li class="nav-item">
                  <a class ="nav-link" href="{% url 'blogapp:gallery' %}">Galeria</a>
                </li>                
                <li class="nav-item">
                  <a class ="nav-link" href="{% url 'api:api' %}">API</a>
                </li>
              </ul>
            </div>
            <div class="col-lg-4 col-6 d-flex flex-column align-items-center py-3">
              <h5 class="text-center fs-4 ff-rd">REJESTRACJA</h5>
              <ul class= "nav flex-column mt-2d">                
                <li class="nav-item">
                  <a class ="nav-link" href="{% url 'users:register' %}">Zarejestruj się</a>
                </li>
                <li class="nav-item">
                  <a class ="nav-link" href="{% url 'users:login' %}">Zaloguj się</a>
                </li>
                <li class="nav-item">
                  <a class ="nav-link" href="{% url 'blogapp:terms' %}">Regulamin</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="text-center">              
          <p class="text-muted"> © Copyright 2022. Strona została wykonana w celach prezentacyjnych. Treść pochodzi z portralu <a class ="" href="https://pl.wikipedia.org/">Wikipedia</a>
            i źródeł licencji Creative Commons. </p>
        </div>               
      </footer>
    <!-- BOOTSTRAP 5 SCRIPT -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body> 
</html>

blogapp/templates/blogapp/delete_topic.html
{% extends 'blogapp/base_container.html' %}
{% load static %}
{% block content %}

<header class="p-3 border-bottom mb-5">
    <i class="fa-solid fa-file-circle-xmark fa-2xl"></i>
    <span class="fs-4 ms-3 fw-bold">Usuń temat: {{topic.title}}</span>
</header>
  
<div class="alert alert-danger text-center mt-3 mx-auto" style="max-width:80%;" role="alert">
    <h5 class="fw-bold">Czy na pewno chcesz usunąć temat "<a class="text-decoration-none link-danger" href="{% url 'blogapp:topic' topic.id %}">{{topic.title}}</a>"?</h5>
        {% if topic.header_image %}
        <img class="img-fluid user-select-none p-3" style="max-width:60%; border-radius: 30px;" src="{{topic.header_image.url}}">  
        {% else %}
        <img class="img-fluid user-select-none p-3" style="max-width:60%; border-radius: 30px;" src="{% static 'images/_defaults/default_topic.png' %}">  
        {% endif %}            
    <p>Powiązane dane zostaną utracone nieodwracalnie.</p>
      <form class="d-inline ms-1" action="{% url 'blogapp:delete_topic' topic.id %}" method = 'post'>
        {% csrf_token %}
        <button type="sumbit" class="btn btn-danger ff-rd" name='submit'>Usuń</button>
      </form>
      <form class="d-inline me-1" action="{% url 'blogapp:index' 0 %}" method ='get'>        
        <button type="sumbit" class="btn btn-secondary ff-rd" name='submit'>Wróć</button>
      </form>
      
      
    
  
</div>
{% endblock content %}

blogapp/templates/blogapp/my_topics.html
{% extends 'blogapp/base_container.html' %}
{% block content %}

<header class="p-3 border-bottom mb-5">
    <i class="fa-solid fa-folder-open fa-2xl"></i>
    <span class="fs-4 ms-3 fw-bold">Moje tematy</span>
</header>

{% if topics %}
<table class="table">
  <thead>
    <tr class="text-secondary">
      <th scope="col">Tytuł</th>
      <th scope="col">Utworzono</th>
      <th scope="col">Zmodyfikowano</th>
      <th scope="col">Edytuj</th>
      <th scope="col">Usuń</th>
      <th scope="col">Status</th>

    </tr>
  </thead>
  <tbody>
    {% for topic in topics %}
      <tr>
        <td class=""><a class="text-decoration-none fst-italic text-dark" href="{% url 'blogapp:topic' topic.id %}">{{topic.title}}</a></td>
        <td class="">{{topic.date_created|date:"d-m-y"}}; {{topic.date_created|time:"H:i"}}</td>
        <td class="">{{topic.date_modified|date:"d-m-y"}}; {{topic.date_modified|time:"H:i"}}</td>
        <td class="ps-4"><a class="link-secondary" href="{% url 'blogapp:edit_topic' topic.id %}"><i class="fa-solid fa-pen-to-square"></i></a></td>
        <td class="ps-4"><a class="link-secondary" href="{% url 'blogapp:delete_topic' topic.id %}"><i class="fa-solid fa-trash-can"></i></a></td>
        {% if topic.confirmed %}
          <td>Zatwierdzony</td>
        {% else %}
          <td>Oczekuje na zatwierdzenie</td>
        {% endif %}
      </tr>      
    {% endfor %}
  </tbody>
</table>
{% else %}
<p class="p-3 fw-bold text-center">Nie dodałeś jeszcze żadnego tematu.<br><a class="link-dark fs-3" href="{% url 'blogapp:new_topic' %}">Dodaj temat</a></p>
{% endif %}



  



{% endblock content %}

blogapp/templates/blogapp/pending_topics.html
{% extends 'blogapp/base_container.html' %}
{% block content %}

<header class="p-3 border-bottom mb-5">
    <i class="fa-solid fa-file-circle-question fa-2xl"></i>
    <span class="fs-4 ms-3 fw-bold">Oczekujące tematy</span>
</header>

{% if topics %}
<table class="table">
  <thead>
    <tr class="text-secondary">
      <th scope="col">Tytuł</th>
      <th scope="col">Utworzono</th>
      <th scope="col">Zmodyfikowano</th>
      <th scope="col">Autor</th>
      <th scope="col">Edytuj</th>
      <th scope="col">Usuń</th>
      <th scope="col">Zatwierdź</th>
    </tr>
  </thead>
  <tbody>
    {% for topic in topics %}
      <tr>
        <td><a class="text-decoration-none fst-italic text-dark" href="{% url 'blogapp:topic' topic.id %}">{{topic.title}}</a></td>
        <td>{{topic.date_created|date:"d-m-y"}}; {{topic.date_created|time:"H:i"}}</td>
        <td>{{topic.date_modified|date:"d-m-y"}}; {{topic.date_modified|time:"H:i"}}</td>
        <td ><a class="text-dark" href="{% url 'users:view_account' topic.owner.username %}">{{topic.owner}}</a></td>
        <td class="ps-4"><a class="link-secondary" href="{% url 'blogapp:edit_topic' topic.id %}"><i class="fa-solid fa-pen-to-square fa-xl"></i></a></td>
        <td class="ps-3"><a class="link-secondary" href="{% url 'blogapp:delete_topic' topic.id %}"><i class="fa-solid fa-trash-can fa-xl"></i></a></td>
        <td>
          <form action="{% url 'blogapp:confirm_topic' topic.id %}" method ='post'>
            {% csrf_token %}
            <button type ='submit' class="btn btn-secondary btn-sm ms-4 rounded-circle text-light">&#10003;</button>
          </form>
        </td>        
      </tr>      
    {% endfor %}
  </tbody>
</table>
{% else %}
  <p class="p-3 fw-bold text-center">Brak tematów oczekujących na zatwierdzenie</p>
  <p class="text-center"><i class="fa-light fa-loader"></i></p>
{% endif %}

{% endblock content %}